export const REGISTERATION_REQUEST = "REGISTERATION_REQUEST";
export const REGISTERATION_SUCCESS = "REGISTERATION_SUCCESS";
export const REGISTERATION_FAILURE = "REGISTERATION_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const PROFILE_REQUEST = "PROFILE_REQUEST";
export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const PROFILE_FAILURE = "PROFILE_FAILURE";

export const LOGOUT = "LOGOUT";

export const GET_TODOS_REQUEST = "GET_TODOS_REQUEST";
export const GET_TODOS_SUCCESS = "GET_TODOS_SUCCESS";
export const GET_TODOS_FAILURE = "GET_TODOS_FAILURE";

export const SET_TODOS_REQUEST = "SET_TODOS_REQUEST";
export const SET_TODOS_SUCCESS = "SET_TODOS_SUCCESS";
export const SET_TODOS_FAILURE = "SET_TODOS_FAILURE";

export const EDIT_TODOS_REQUEST = "EDIT_TODOS_REQUEST";
export const EDIT_TODOS_SUCCESS = "EDIT_TODOS_SUCCESS";
export const EDIT_TODOS_FAILURE = "EDIT_TODOS_FAILURE";